name: App Test

on:
  pull_request:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Tests with Gradle Wrapper
        run: ./gradlew test
